### ISSUE TITLE
matterhorn requires /etc/localtime

### ISSUE THREAD

**Issue by sfischme** [cdrage/dockerfiles#4]
Matterhorn requires /etc/localtime.

The image can be used as is, but requires this to launch:
```
 docker run -it --rm \
  -v /etc/localtime:/etc/localtime \
  -e MM_USER=foobar@domain.com \
  -e MM_PASS=foobar \
  -e MM_HOST=gitlab.mattermost.com \
  -e MM_PORT=443 \
  --name matterhorn \
  cdrage/matterhorn
```

Otherwise, it's crashing at the moment.

**Comment by cdrage** [comment]
Thank you! Sorry about the MASSIVE 4 year delay. Going to update this lol.
